### ISSUE TITLE
Failed to build with io.js@1.0.2

### ISSUE THREAD

**Issue by redism** [msgpack/msgpack-node#20]
node-gyp comes with io.js@1.0.2 fails to build msgpack. Just updating nan module version to the latest fixes the issue and pass all the tests.

**Comment by redism** [comment]
iojs/io.js#456

**Comment by hmalphettes** [comment]
`npm i msgpack` works fine with iojs and node-0.12 now: we can close this.

**Comment by godsflaw** [comment]
great, thanks.  Let me know if you still have problem @redism
