### ISSUE TITLE
Node JS 0.10.37 compatibility

### ISSUE THREAD

**Issue by razvip91** [msgpack/msgpack-node#30]
Hi there,

I'm trying to build msgpack@1.0.2 for zerorpc and it fails with ELIFECYCLE error from npm. What are the compatible versions with nodejs 0.10.37. If there are multiple compatibilty issues, then a compatibility table would be a nice documentation improvement. Thanks

**Comment by blackdynamo** [comment]
Hey, I added a pull request that should let you use with node 0.10.x+. Pull request https://github.com/msgpack/msgpack-node/pull/35.

Older versions work on older versions of node, was using 0.2.6. This simple change will allow you to update to the latest.

**Comment by razvip91** [comment]
Hey, thanks for this, but in the meantime we upgraded to node 0.12.7 (for now). But if the need occurs, it's good to have this pull request.

Thanks again.
