### ISSUE TITLE
Update to modern NodeJS versions?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [msgpack/msgpack-node#45]
Is this library still maintained? I'm getting
```
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/home/ubuntu/stardust-backend/node_modules/msgpack/build/Release/msgpackBinding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

And I don't see any commits past 2015 in this repo.

**Comment by strugee** [comment]
This is not `msgpack`'s fault. `msgpack` is a binary module which means it was automatically compiled when you `npm install`'d it. Since you upgraded Node, the version on your system is now built against your old Node version.

Run `npm rebuild` to fix.

**Comment by GeoffreyPlitt** [comment]
Gotcha, thanks
